[package]
name = "mirl_build_tools"
version = "0.0.0-alpha"
edition = "2024"
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["margin"]
miri = []
all = ["serde", "bitcode", "wincode", "strum", "enum_ext"]
# Compatibility with ffi
c_compatible = []
# Enables all codecs
all_codecs = ["serde", "bitcode", "wincode", "compactly", "zerocopy"]
# All enum extensions
all_enum_extensions = ["strum", "enum_ext"]
# Codec stuff
serde = ["dep:serde"]
bitcode = ["dep:bitcode"]
wincode = ["dep:wincode"]
compactly = ["dep:compactly"]
zerocopy = ["dep:zerocopy"]
# Enum extensions
strum = ["dep:strum"]
enum_ext = ["dep:enum_ext"]
border = ["terminal_size"]
margin = ["border"]
force_unicode = []
force_ascii = []
force_code_page_437 = []
_checking = ["all"]

[dependencies]
bitcode = { version = "0.6", optional = true, default-features = false, features = [
    "derive",
] }
# Codec
compactly = { version = "0.2", optional = true }
enum_ext = { version = "0.6", optional = true, default-features = false }
mirl_macros = { version = "0.0.0-alpha" }
serde = { version = "1.0", optional = true, default-features = false, features = [
    "derive",
    "std",
] }
simd-json = { version = "0.18", default-features = false, features = [
    "runtime-detection",
] }
# Enum functionality
strum = { version = "0.28", optional = true, default-features = false, features = [
    "derive",
] }
terminal_size = { version = "0.4", optional = true }
version_check = "0.9"
wincode = { version = "0.6", optional = true, features = ["derive"] }
zerocopy = { version = "0.8", optional = true, default-features = false, features = [
    "float-nightly",
    "derive",
] }

[lints]
workspace = true
